### ISSUE TITLE
Going into an interior will sometimes trigger a loop of going in and back out

### ISSUE THREAD

**Issue by martinloeffen** [PTPM/MTASA#11]
But I've never heard anyone complain about it but me, and I'll workaround it, so kinda minor

**Comment by martinloeffen** [comment]
Will test and report back any changes

**Comment by martinloeffen** [comment]
It happened to me again: https://stjohnsmorgue.rip/s/2BuZjxgE.mp4 (LS Mall interior)
And also to some other poor saps: https://stjohnsmorgue.rip/s/WnmMcx0h.mp4 (PTPM LS Hydra safehouse interior)

**Comment by martinloeffen** [comment]
Reposting comment from Remp about the issue 

[18:00:49] <&Remp> very weird
[18:01:02] <&Remp> what's really strange is that in your video it looks like it happens when you leave the marker
[18:01:50] <&Remp> which makes no sense since it doesn't even use the collider exit events
[18:02:33] <&uhm> yes
[18:03:07] <&Remp> it's like mta isn't triggering the enter event until you leave
[18:03:24] <&Remp> like it doesn't realise you've been teleported into it or something

**Comment by martinloeffen** [comment]
I haven't finished my analysis yet, but I set up another instance of the mtaserver at port mtasa://play-mtasa-srv1.ptpm.uk:22013 and the issue does NOT occur when I'm the only person present in the server. Will try again with a second client connected.

**Comment by martinloeffen** [comment]
It feels like it doesn't happen nearly as often. I tried locally, and on Testing and it happened zero times on those. Then I went on Production and it didn't happen (also tested that one house in Countryside, the one from the first video). So then I set my resolution back to 1920x1080, and it happened twice then (on the same marker, Desert Flight School).  And then I found out that if you jump into a marker, it won't trigger (not a bug per se)

https://stjohnsmorgue.rip/s/ReLY4CSz.mp4
Intdump: https://stjohnsmorgue.rip/s/nn2EN2Uj.txt

**Comment by martinloeffen** [comment]
https://www.youtube.com/watch?v=P-2VgfhQuUQ
https://stjohnsmorgue.rip/s/Q6u4tXC2.txt

**Comment by RempRemp** [comment]
This certainly looks like an mta issue. The col shape enter/leave events and triggering over and over (~a dozen times in a few ms) even though the player isn't actually moving. I'm not really sure why.

I have refactored again to try and work around this (2b1136cb34e2abbc84843bf23c2c11e6cff381e3)

**Comment by martinloeffen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Interiors](https://trello.com/c/g8oGyMbi/41-interiors)

**Comment by RempRemp** [comment]
This is still happening

**Comment by martinloeffen** [comment]
Still

**Comment by RempRemp** [comment]
Last commit attempts to just work around the problem (whatever it actually is). If this doesn't work i'll revert everything and start from the base version again until we can figure out what is happening.

**Comment by martinloeffen** [comment]
Unfortunately, it still happens.

What if we just give the guy godmode for 3 seconds upon entering an interior, and cancel it as soon as they shoot. Are No.2 and No.3 the only ones fixed by the interiors resource scripts? (https://ptpm.uk/index.php/topic,553.msg4791.html#msg4791)

**Comment by RempRemp** [comment]
Nah, the int dumps aren't really needed now. Yes, 2 and 3 are the only ones. I would be astonished if either of those things actually related to this problem though, and they would be easy enough to re-apply, unlike the general refactoring which would be a pain to redo

**Comment by martinloeffen** [comment]
Game server, 18 February 2017
> [21:26] Remp: are interiors fixed now?
[21:26] kaevix: ye remp
[21:26] R1-one: it seems like it remp
[21:26] Remp: hooray

I also haven't noticed any issues any more, so assuming fixed.
