### ISSUE TITLE
Heligrab throws a lot of warnings when new map starts

### ISSUE THREAD

**Issue by martinloeffen** [PTPM/MTASA#16]
https://stjohnsmorgue.rip/s/2WiS8er.png

**Comment by RempRemp** [comment]
This won't have caused any problems, but it should now stop erroring. The fact that it happens at all is a little worrying, it means mta is triggering onClientElementDestroy with nil elements which doesn't make any sense (and is clearly not right), and could potentially be causing problems elsewhere
