### ISSUE TITLE
strategy_radial: unplayable on AZERTY keyboards

### ISSUE THREAD

**Issue by martinloeffen** [PTPM/MTASA#18]
On an AZERTY keyboard, the menu will open and prevent movement. Currently, resource is disabled.
Solution: to rework the system to use the MTA bind system and set the default binds to unused keys, or maybe no keys at all.

**Comment by martinloeffen** [comment]
(it's actually not a bug, it's a design flaw)

**Comment by RempRemp** [comment]
Try it with the changes in 48df007c9517d24e1a65e25d895f522be8bdaf8f, it should be usable now
