### ISSUE TITLE
strategy_radial mysteriously stopped working

### ISSUE THREAD

**Issue by martinloeffen** [PTPM/MTASA#26]

**Comment by martinloeffen** [comment]
No idea what caused it, perhaps PTPM has to be running for the event handlers to kick in? Maybe it stopped working after an update and refreshall reloaded the scripts in an incompatible sequence?

```lua
addEventHandler( "ptpmStartMapVote", localPlayer, function() overwriteDisableStrategyRadial = true end )
addEventHandler( "enterClassSelection", localPlayer,  function() overwriteDisableStrategyRadial = true end ) 
addEventHandler( "leaveClassSelection", localPlayer,  function() overwriteDisableStrategyRadial = false end )
```

**Comment by RempRemp** [comment]
Probably. You could test pretty easily locally starting/stopping in different orders. You should add events that you use from external resources so you can guarantee they exist, regardless of start order. e.g. addEvent("enterClassSelection", true). If you try to add a handle for an event that doesn't exist it will just fail. It doesn't matter which resource registers the event first, as long as they are registered with the same args

We should probably just export a function from ptpm to check if the player is in the class selection/endgame though, i think that makes more sense than how it currently works

**Comment by RempRemp** [comment]
Updated to use ptpm exports in eb1570d22ddd3036c4414743f2221e90a16ca206

**Comment by martinloeffen** [comment]
Verified to work after a refreshall without interference
