### ISSUE TITLE
Vehicle_weapons does not work as expected

### ISSUE THREAD

**Issue by anonymous-d0z42ujxuog5** [PTPM/MTASA#30]
In Production

**Comment by martinloeffen** [comment]
In Production

**Comment by martinloeffen** [comment]
Conflicts with realdriveby (higher fire rate). It does not work most of the time. Sometimes it briefly showed the HUD for regular vehicles.

Currently script disabled.

**Comment by martinloeffen** [comment]
Should be reworked anyway to work like realdriveby, rather than binding it to onPreRender

**Comment by martinloeffen** [comment]
Reworked as stated and put live. No compatibility issues with realdriveby have been detected.

**Comment by martinloeffen** [comment]
vehicle_nerf still doesn't work as expected, effect also applies to Rustlers and Seasparrows. Could it be the server-to-client delayed trigger? Maybe it isn't sent right

**Comment by martinloeffen** [comment]
I remember that I was able to shoot with a Rustler right after take-off but a while later it said 0 ammo.

**Comment by martinloeffen** [comment]
https://github.com/PTPM/MTASA/commit/088f4627652c64ada35d10ff162df7bef29d4f96

**Comment by martinloeffen** [comment]
> [18:40:35] <&uhm> ah fuck vehicle_nerf seems to be glitched still
[18:40:44] <&uhm> i went from 50 ammo to 25 to 4 to 0


Could this be an issue with setElementData?

**Comment by RempRemp** [comment]
No, i would be extremely surprised if there is anything wrong with element data. The issue is almost certainly somewhere else
