### ISSUE TITLE
MTASA paraglitch 

### ISSUE THREAD

**Issue by anonymous-d0z42ujxuog5** [PTPM/MTASA#33]
This is an issue in the parachute resource:

* It does not offer to let you open your parachute sometimes
* It happens more often to players with a higher ping
* It would seem that the serverside decides whether client is allowed to parachute, but it's not always correct

**Comment by RempRemp** [comment]
Parachute is almost completely clientside, the server only syncs the state changes. Every client has complete control over their own parachuting state. I'm not sure this (as described) is an issue at all. Not being able to parachute sometimes does happen but it's for well defined reasons (i.e. an object underneath you), I've never seen or heard of it happening at any other (unexplained) time

The post on the forum (that this was presumably taken from) is talking about a different thing, that the parachute will sometimes accelerate when opened. I've seen similar-ish things myself, but i don't really know what is going on to cause it, and its possible that people are talking about a few different effects. It would probably be good to get a video
